test:
  address: "smtp.gmail.com"
  port: "587"
  domain: "localhost"
  authentication: "plain"
  user_name: "benabcd123456@gmail.com"
  password: "runyonrails"
  enable_starttls_auto: true
development:
  address: "smtp.gmail.com"
  port: "587"
  domain: "localhost"
  authentication: "plain"
  user_name: "benabcd123456@gmail.com"
  password: "runyonrails"
  enable_starttls_auto: true
production:
  address: "smtp.gmail.com"
  port: "587"
  domain: "localhost"
  authentication: "plain"
  user_name: "benabcd123456@gmail.com"
  password: "runyonrails"
  enable_starttls_auto: true